Each tarball contains the MESA input files (=inlists= and
=src/run_star_extras.f=, =src/run_binary_extra.f=), the output, and
checkpoints across the evolution (=*.mod=).  The numerical results
(selected =LOGS*/profiles*= files, =LOGS*/history.data= and
=binary_history.data= files) are also included, together with =pgstar=
plots (inside =png/=).

The simulations were computed with [[http://mesa.sourceforge.net/][MESA]] version r15140 with the [[http://www.astro.wisc.edu/~townsend/static.php?ref=mesasdk][MESA SDK]] x86_64-linux-20.12.1.

* fiducial.tar.xz

  Contains the fiducial model described in Sec. 3 (M1=25Msn,
  M2=17Msun, P=100, Z=0.01).

* do_J_accretion.tar.xz

  Contains the model following [[https://ui.adsabs.harvard.edu/abs/2013ApJ...764..166D/abstract][de Mink et al. 2013]] for the accretion
  of angular momentum.

* M1_30.tar.gz

  Contains the model with M1=30Msun (the rest being equal to the fiducial
  model).

* M1_25_M2_17_P75_Z0.01.tar.xz

  Contains the model with P=75days (the rest being equal to the fiducial
  model).

* Z_0.0142.tar.xz

  Contains the model with Z=0.0142 (the rest being equal to the fiducial
  model)

* ES_10x_lower.tar.xz

  Contains the model reducing the efficiency of Eddington-Sweet
  circulations by a factor of 10 compared to the fiducial model, down
  to 0.033.

* single_stars.tar.xz

  Contains all the single stars shown in the paper: non-rotating stars
  of varying mass (dashed gray lines in Fig. 1), and rotating stars of
  20Msun with varying initial rotation rates.

* Brott+11_ov.tar.xz

  Model using the core overshooting from [[https://ui.adsabs.harvard.edu/abs/2011A%26A...530A.116B/abstract][Brott et al. 2011]].

* space_res.tar.xz

  Contains the higher spatial resolution models from appendix A (only
  binary evolution).

* mix_movie.mp4

  Movie of the mixing processes inside the accretor star (cf. Fig. 4).

* composition_accretor.mp4

  Movie of the hydrogen, helium, carbon, nitrogen, and oxygen
  abundances in the accretor star.
