* Evolution of accretor stars in massive binaries: broader implications from modeling \zeta Ophiuchi
authors: [[mailto:mrenzo@flatironinstitute.org][Mathieu Renzo]], Ylva Goetberg

Code for reproducing the numerical results of [[https://arxiv.org/abs/2107.10933][arXiv:2107.10933]], submitted to
the Astrophysical Journal.

We used [[http://mesa.sourceforge.net/][MESA]] version r15140 with the [[http://www.astro.wisc.edu/~townsend/static.php?ref=mesasdk][MESA SDK]] x86_64-linux-20.12.1.

The data produced are available at [[https://doi.org/10.5281/zenodo.4701565]].

** Setup of the MESA simulations

*** Binary evolution

    The setup for our binary evolution runs, until the
    post-mass-transfer detachment is in
    =MESA_setup/binary_to_postRLOF=. This is a MESA work directory for a
    binary system. To use it you need to change =MASS1=, =MASS2=, and
    =PERIOD= to the appropriate values in
    =MESA_setup/binary_to_postRLOF/inlist_binary=, and =METALLICITY= in
    =MESA_setup/binary_to_postRLOF/inlist_both=.

*** Continuation of the accretor as a single star

    We restart the evolution of the accretor from a model saved in the
    binary run. The MESA work directory =MESA_setup/accretor_to_TAMS= is
    used for this purpose. You need to modify
    =MESA_setup/accretor_to_TAMS/inlist_extra= to point it to the
    location of the MESA model (=*.mod= file) saved at the end of the
    binary run by modifying =saved_model_name=, and modify =ZBASE=
    to be the initial metallicity of the model.

*** Single stars

    The single star models are produced with the
    =MESA_setup/single_rotating_stars= work directory. You need to set
    explicitly the initial \omega/\omega_{crit} and mass wanted in =inlist_extra=.


** notebooks/

   Inside =notebooks/= you can find the scripts to reproduce the
   numerical analysis of our models and the figures. Many auxiliary
   functions are defined in =plot_aux.py=, and the notebooks also rely
   on [[https://github.com/mathren90/plotFunc]]. The other dependencies
   are listed in =pyproject.toml=.

*** Figure 1 and 2

    The code to reproduce Fig. 1 and 2 is in
    =notebooks/Best_model.ipynb=.

*** Figure 3-7

    The code to reproduce Fig. 3-7 is in =notebooks/mixing_and_AM.ipynb=.

*** Figure 8

    The code to reproduce Fig. 8 and the resolution tests is in =notebook/resolution_test.ipynb=.

*** Table 1

    The code to create Table 1 is in =notebooks/table.ipynb=.

** data/

   Contains the /Gaia/ DR3 data for \zeta Ophiuchi. These are
   unfortunately not usable (large RUWE)

** movies/

   Contains the movies of the mixing processes and chemical
   composition of our accretor models.

** manuscript/

   This folder is probably not interesting to you. It contains the =tex=
   file and other auxiliary files for the paper associated to this
   repository. Unlike the rest of the repository, licensed with GPLv3,
   that subfolder is licensed with CC BY-NC-ND 3.0.
