* \zeta Ophiuchi

author: [[mailto:mrenzo@flatironinstitute.org][Mathieu Renzo]]

Project on self-consistent MESA modeling of [[http://simbad.u-strasbg.fr/simbad/sim-id?Ident=zeta+ophiuchi&NbIdent=1&Radius=2&Radius.unit=arcmin&submit=submit+id][\zeta ophiuchi]]

** \zeta Ophiuchi's observational literature

This doesn't mean to be a comprehensive list, and it is in no
particular order:

[[https://ui.adsabs.harvard.edu/abs/2014ApJS..211...10S/abstract][Sota et al. 2014]], [[https://www.aanda.org/articles/aa/pdf/2005/40/aa2848-05.p][Villamariz & Herrero 2005]], [[https://ui.adsabs.harvard.edu/abs/2001MNRAS.327..353H/abstract][Howarth & Smith 2001]],
[[https://ui.adsabs.harvard.edu/abs/2010MNRAS.402.2369T/abstract][Tetzlaff al. 2010]], [[https://ui.adsabs.harvard.edu/abs/2011MNRAS.410..190T/abstrac][Tetzlaff et al. 2011]], [[https://ui.adsabs.harvard.edu/abs/1952BAN....11..414B/abstract][Blaauw 1952]], [[https://ui.adsabs.harvard.edu/abs/1961BAN....15..265B/abstract][Blaauw 1961]],
[[https://ui.adsabs.harvard.edu/abs/2020MNRAS.498..899N/abstract][Neuhauser et al. 2020]], [[https://ui.adsabs.harvard.edu/abs/2018AN....339...46Z/abstrac][Zehe et al. 2017]], [[https://ui.adsabs.harvard.edu/abs/2009A%26A...498..837M/abstract][Marcolino et al. 2009]].

From its runaway nature we know it is associated to PSR B1929+10 (PSR
J1932+1059) their parent association is probably Upper Scorpio in Sco
OB1 which is likely to be slightly sub-solar Z based on the precision
fitting of pre-MS asteroseismology of one star by [[https://ui.adsabs.harvard.edu/abs/2020arXiv201111821M/abstract][Murphy et al. 2021]].
Indeed, Z lower than Zsun is required to fit the temperature required
by Villamariz & Herrero 2005.

** Miscellaneous notes

*** MESA

Right now MESA evolves a binary until the donor's He core depletion.
If one wants to push the evolution of the accretor to TAMS, you should run
it separately as a single star (to avoid the difficult computation of
the very late phases for the donor to be the bottleneck). MESA saves a
model that can be used as initial condition for this, alternatively
one can use a photo. Preliminary tests show this is equivalent.

*** Metallicity

The =\varepsilon(oxygen)= reported in Villamariz & Herrero 2005
corresponds to the Solar value according to Asplund 2005 (cf. Japeli
et al. 2018). There is no way to enhance oxygen through binary
interactions and/or rotational mixing, so this is a good indicator of
the initial Z (or suggests a non-solar mixture).

*** Kinematics

Unfortunately the ~ruwe~ for \zeta Ophiuchi is >4, so EDR3 is
useless. I suspect this is due to the stellar variability and the very
large visual magnitude ~Mv = -4.2~.

Tetzlaff et al. 2010 mention ~ ~20km/s~ for \zeta Ophiuchi's space
velocity, dominated by its large proper-motion. This is a local
standard frame velocity corrected for Galactic rotation. However, [[https://ui.adsabs.harvard.edu/abs/1961BAN....15..265B/abstract][Blaauw 1961]]
quotes 39km/s. [[https://ui.adsabs.harvard.edu/abs/1952BAN....11..414B/abstract][Blaauw 1952]]
quotes 31km/s just for the transverse motion. Note that Blaauw's
numbers are not relative to Upper Scorpio. [[https://ui.adsabs.harvard.edu/abs/2018AN....339...46Z/abstrac][Zehe et al. 2017]] questions
the radial velocity used in Hoogerwerf et al. 2001, and Neuhauser et
al. 2020 updated the kinematics and identify Upper Centaurus Lupus
rather than Upper Scorpio as most likely origin, and a different
pulsar for the companion.

The [[https://ui.adsabs.harvard.edu/abs/1996A%26A...305..825V/abstract][Vanrensbergen et al. 1996]] paper quotes a 46km/s 3D velocity
with respect to SCO OB2. This was derived assuming RV=18km/s and
42km/s of transverse velocity.

[[https://ui.adsabs.harvard.edu/abs/2018AN....339...46Z/abstrac][Zehe et al. 2017]] claim a RV of 12.2+/- 3.3 km/s

*** Parameters that matter for the orbital velocity

How conservative mass transfer is (in other words, how the mass ratio
evolves), what angular momentum it loses. This is turn can depend on
the prescription for spin-up/spin-down of the accretor. This are being
assumed right now.

*** Notes on the parent association

Based on the proper motion alone, Blaauw 1952 suggested the parent
association might be the Upper Scorpio association of SCO
OB2. Although [[https://ui.adsabs.harvard.edu/abs/1996A%26A...305..825V/abstract][Vanrensbergen et al. 1996]] could not find a suitable
binary evolution model for \zeta Ophiuchi and excluded this region,
Tetzlaff et al. 2010 reconsidered the star kinematics and the
kinematics of a pulsar (PSR 1929+10) and concluded a common origin in
Upper Scorpio about 1 Myr ago. Neuhauser et al. 20 updated this result
with a different pulsar identified as best companion, and not US but
UCL as region of origin.

The age of Upper Scorpio is not well known,
[[https://ui.adsabs.harvard.edu/abs/2015MNRAS.448.2737R/abstract][Rizzuto et al. 2015]] place it between 5-10Myr, which implies 4-9Myr at
the explosion, i.e. a donor ZAMS mass larger than 20Msun. Note however
that the latest results from Neuhauser et al. 2020 suggest UCL as the
parent association, not US.

The metallicity is likely to be slightly sub-solar Z based on the precision
fitting of pre-MS asteroseismology of one star by [[https://ui.adsabs.harvard.edu/abs/2020arXiv201111821M/abstract][Murphy et
al. 2020]]. However, Villamariz & Herrero 2005 report a solar abundance
of Oxygen and Carbon, maybe there is a different mixture of elements?
Note that UCL and US might have slightly different Z, although both
regions and SCO OB2 as a whole is probably too young to have had SN Ia
enriching significantly in iron (but on the other hand, Neuhauser et
al. 2020 propose the explosions that released \zeta Ophiuchi polluted
earth with fe60).

For an overview of the SCO OB2 in the Hipparcos data and Upper
Scorpio, see [[https://ui.adsabs.harvard.edu/abs/1999AJ....117..354D/abstract][de Zeeuw et al. 1999]].

Neuhauser et al. 2020 report a flight time of ~1.5Myr (which
uncertainties dominated by the unknown pulsar velocity), and PSR
B1706-16 as the most likely companion NS, in contrast to previous
results by Hoogerwerf et al. and Tetzlaff et al. 2010. The update is
mostly due to the RV from Zehe et al. 2018. This would put the origin
of this system in UCL and not US. UCL has an estimated age of 10-20
Myr, so brings down the donor's initial mass to 10-20Msun. The
peculiar space velocity with respect to the LSR quoted by Neuhauser et
al. 2020 is 19.7km/s.

**** TODO Papers to check

 - [] Wright & Mamajek 2018 for kinematics of parent association

*** Weak wind problem

[[https://ui.adsabs.harvard.edu/abs/2009A%26A...498..837M/abstract][Marcolino et al. 2009]] studied the weak wind problem modeling also
\zeta Ophiuchi. They find winds weaker than predicted by Vink et
al. 2001, which would help keeping up the rotation rate and accrete
more even at higher Z.

The factor by which the wind should be decreased is ~10^-2.2, however
already reducing by a factor of ~10x the wind in MESA the very fast
rotating accretor stars go crazy as they evolve towards the end of the
main sequence. Running now with just a factor of 3x decrease, just to
prove the point than more AM would remain, though it is insufficient
to address the weak wind problem. This is because the core
contraction would already tend to spin them up, but they are already
critically rotating because of the mass transfer.

On the other hand, lowered winds would significantly help mantaining
for longer the high rotation rate observed.

*** Mass of \zeta Ophiuchi

Masses are inferred from taking the log_g of (rotating) single star
models. This seems to lead to low-ish mass values incompatible with
the high Teff observed.

*** Note on the donor star

At He depletion the masses of the donor stars range form 6.5-9Msun
(depending on the initial donor mass and the period and mass ratio). A
6.5Msun stripped core at He depletion has \lesssim 10^4 years to live,
so this can be neglected when aiming at the kinematic age and
abundances match

*** Staircase in the HRD

It is most severe when thermohaline mixing start mixing the newly
accreted material with the pre-existing envelope.

This can be reduced to small variations by adjusting

#+BEGIN_SRC fortran90

max_timestep_factor = 1.05d0
retry_hold = 5
min_J_div_delta_J = 50d0 ! 3d0

#+END_SRC

in particular the last one seem to lead to noisiness in the spin down.

**** TODO maybe try reducing =max_mdot_jump_for_rotation=
*** Problems with the CHE scenario

    \zeta Ophiuchi has undeniably a very fast rotation rate and shows
    He enhancement. However, its C, N, O surface abundance are
    "normal". This is in contrast with the typical predictions of CHE.
    [[https://ui.adsabs.harvard.edu/abs/2007A%26A...465L..29C/abstract)][Cantiello et al. 2007]] proposed that accretors in binaries would
    lead to CHE and become GRB progenitors. While this remains a
    possibility, it might not be always the case -- especially since
    \zeta ophiuchi clearly is not a low Z star, and rotational mixing
    is more efficient at low Z. In particular, they
    also showed that the accretor would evolve very similarly to a
    single star fast rotating from ZAMS. However Villamariz & Herrero
    2005 where unable to find a good match for \zeta Ophiuchi using
    the rotating GENEVA models.


** TODO Questions

*** Why left-ward HRD movement when becoming single star?

This does not depend on the timestep resolution. Does it have to do
with the thermohaline mixing?

*** Why blips mid-way through HRD?

Is it some convective shell behavior? Or is it related to the AM
redistribution in the star?

*** Morphology of mass transfer

**** max extension

     The model turns around when it reaches omega_div_omega_crit>0.95

**** v-shape

     Possibly related to mixing of initial material and newly accreted
     material? NO! That is when the stair-case becomes severe. The
     v-shape is earlier.

     Possibly related to omega_div_omega_crit? NO! there doesn't seem
     to be any variation in omega_div_omega_crit at the v-shape.

     Possibly related to the donor reaching the minimum luminosity
     during mass transfer and change in the composition of the stuff
     coming in, maybe more He rich? This appears to be correct!

**** thermohaline loops

     These where found in Cantiello et al. 2007 as well.
     They begin when the thermohaline mixing zone touches the
     convective region that has grown because of accretion.


**** weird loopy at end of RLOF in the donor

     That is the damned surface convection layer that pops up because
     of partial recombination of He.

** TODOs

*** TODO build python dependencies list with poetry
